import fs from "fs";
import path from "path";
import matter from "gray-matter";
import { domains, getCategories } from "../src/lib/domains";

const CONTENT_DIR = path.join(process.cwd(), "content");
const OUTPUT_FILE = path.join(process.cwd(), "src/lib/static-content.ts");

interface ArticleData {
  slug: string;
  domain: string;
  category: string;
  title: string;
  date: string;
  updated?: string;
  summary: string;
  tags: string[];
  group: string;
  draft: boolean;
  content: string;
}

function readMdxFiles(dirPath: string): { slug: string; raw: string }[] {
  if (!fs.existsSync(dirPath)) return [];
  const files: { slug: string; raw: string }[] = [];
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  for (const entry of entries) {
    if (
      entry.isFile() &&
      entry.name.endsWith(".mdx") &&
      entry.name !== "_intro.mdx"
    ) {
      const slug = entry.name.replace(/\.mdx$/, "");
      const raw = fs.readFileSync(path.join(dirPath, entry.name), "utf-8");
      files.push({ slug, raw });
    }
  }
  return files;
}

function readIntroFile(
  dirPath: string
): { raw: string; content: string; data: Record<string, any> } | null {
  const introPath = path.join(dirPath, "_intro.mdx");
  if (!fs.existsSync(introPath)) return null;
  const raw = fs.readFileSync(introPath, "utf-8");
  const { data, content } = matter(raw);
  return { raw, content, data };
}

function main() {
  const articles: ArticleData[] = [];
  const intros: Record<string, Record<string, { content: string; title: string; summary: string }>> = {};

  for (const domain of domains) {
    intros[domain.slug] = {};
    const categories = getCategories(domain.slug);
    
    for (const cat of categories) {
      const catDir = path.join(CONTENT_DIR, domain.slug, cat.slug);
      
      // Read intro file
      const intro = readIntroFile(catDir);
      if (intro) {
        intros[domain.slug][cat.slug] = {
          content: intro.content,
          title: intro.data.title || `${cat.slug} 概览`,
          summary: intro.data.summary || "",
        };
      }
      
      // Read articles
      const files = readMdxFiles(catDir);
      for (const file of files) {
        const { data, content } = matter(file.raw);
        if (data.draft === true) continue;
        
        articles.push({
          slug: file.slug,
          domain: domain.slug,
          category: cat.slug,
          title: data.title || file.slug,
          date: data.date || "1970-01-01",
          updated: data.updated,
          summary: data.summary || "",
          tags: data.tags || [],
          group: data.group || "未分类",
          draft: data.draft || false,
          content,
        });
      }
    }
  }

  // Generate static content file
  const fileContent = `// Auto-generated static content registry
// Generated at: ${new Date().toISOString()}
// Do not edit this file manually

import type { Article, ArticleMeta, SidebarData } from "@/types";
import { domains, getCategories, getDomain } from "./domains";

// Static article data
const articlesData: Article[] = ${JSON.stringify(articles, null, 2)};

// Static intro data
const introsData: Record<string, Record<string, { content: string; title: string; summary: string }>> = ${JSON.stringify(intros, null, 2)};

// Article registry
export const staticArticles: Article[] = articlesData;

// Get all article slugs for generateStaticParams
export function getAllArticleSlugs(): { domain: string; slug: string }[] {
  return staticArticles.map(a => ({ domain: a.domain, slug: a.slug }));
}

// Get article by domain and slug
export function getArticleBySlug(domain: string, slug: string): Article | null {
  return staticArticles.find(a => a.domain === domain && a.slug === slug) || null;
}

// Get articles by domain
export function getArticlesByDomain(domain: string): ArticleMeta[] {
  return staticArticles
    .filter(a => a.domain === domain)
    .map(({ content, ...meta }) => meta)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// Get articles by category
export function getArticlesByCategory(domain: string, category: string): ArticleMeta[] {
  return staticArticles
    .filter(a => a.domain === domain && a.category === category)
    .map(({ content, ...meta }) => meta)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// Get sidebar data
export function getSidebarData(domainSlug: string): SidebarData | null {
  const domain = getDomain(domainSlug);
  if (!domain) return null;
  const categories = getCategories(domainSlug);
  const sidebarCategories = categories.map(cat => {
    const articles = getArticlesByCategory(domainSlug, cat.slug);
    const hasIntro = !!introsData[domainSlug]?.[cat.slug];
    return { ...cat, articles, hasIntro };
  });
  return { domain, categories: sidebarCategories };
}

// Get category intro
export function getCategoryIntro(
  domainSlug: string,
  categorySlug: string
): { content: string; title: string; summary: string } | null {
  return introsData[domainSlug]?.[categorySlug] || null;
}

// Get domain with categories
export function getDomainWithCategories(domainSlug: string) {
  const domain = getDomain(domainSlug);
  if (!domain) return null;
  const categories = getCategories(domainSlug);
  return { ...domain, categories };
}
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, "utf-8");
  console.log(`Generated static registry with ${articles.length} articles`);
  console.log(`Output: ${OUTPUT_FILE}`);
}

main();
