import fs from "fs";
import path from "path";
import { domains, getCategories } from "../src/lib/domains";

const ARTICLES_DIR = path.join(process.cwd(), "articles");
const OUTPUT_FILE = path.join(process.cwd(), "src/lib/static-content.ts");

interface ArticleData {
  slug: string;
  domain: string;
  category: string;
  title: string;
  date: string;
  updated?: string;
  summary: string;
  tags: string[];
  group: string;
  draft: boolean;
  content: string;
}

/**
 * 从 HTML 内容中提取标题（第一个 h1 标签）
 */
function extractTitle(html: string): string | null {
  const h1Match = html.match(/<h1[^>]*>(.*?)<\/h1>/i);
  return h1Match ? h1Match[1].replace(/<[^>]+>/g, "").trim() : null;
}

/**
 * 从 HTML 内容中提取摘要（第一段文字，去除 HTML 标签）
 */
function extractSummary(html: string): string {
  // 移除 script 和 style 标签及其内容
  const cleanedHtml = html.replace(/<(script|style)[^>]*>[\s\S]*?<\/\1>/gi, "");
  
  // 查找第一个段落或第一段文本
  const pMatch = cleanedHtml.match(/<p[^>]*>(.*?)<\/p>/i);
  if (pMatch) {
    return pMatch[1].replace(/<[^>]+>/g, "").trim().substring(0, 200);
  }
  
  // 如果没有 p 标签，尝试获取 h1 后的文本
  const textMatch = cleanedHtml.match(/<h1[^>]*>.*?<\/h1>\s*(.*?)(?:<|$)/i);
  if (textMatch) {
    return textMatch[1].replace(/<[^>]+>/g, "").trim().substring(0, 200);
  }
  
  return "";
}

/**
 * 从文件名生成 slug
 */
function slugify(filename: string): string {
  return filename.replace(/\.html$/, "");
}

/**
 * 读取 HTML 文件
 */
function readHtmlFiles(dirPath: string): { slug: string; content: string; filePath: string }[] {
  if (!fs.existsSync(dirPath)) return [];
  const files: { slug: string; content: string; filePath: string }[] = [];
  const entries = fs.readdirSync(dirPath, { withFileTypes: true });
  
  for (const entry of entries) {
    if (entry.isFile() && entry.name.endsWith(".html")) {
      const filePath = path.join(dirPath, entry.name);
      const content = fs.readFileSync(filePath, "utf-8");
      const slug = slugify(entry.name);
      files.push({ slug, content, filePath });
    }
  }
  
  return files;
}

/**
 * 获取文件修改时间作为日期
 */
function getFileDate(filePath: string): string {
  try {
    const stats = fs.statSync(filePath);
    return stats.mtime.toISOString().split("T")[0];
  } catch {
    return new Date().toISOString().split("T")[0];
  }
}

/**
 * 根据分类推断 group
 */
function inferGroup(category: string): string {
  const groupMap: Record<string, string> = {
    "llm": "大语言模型",
    "machine-learning": "机器学习",
    "prompt-engineering": "提示工程",
    "ai-application": "AI 应用",
    "multimodal-ai": "多模态 AI",
  };
  return groupMap[category] || "未分类";
}

/**
 * 根据分类生成标签
 */
function inferTags(category: string, title: string): string[] {
  const baseTags: Record<string, string[]> = {
    "llm": ["llm", "大模型"],
    "machine-learning": ["ml", "机器学习"],
    "prompt-engineering": ["prompt", "提示工程"],
    "ai-application": ["ai", "应用开发"],
    "multimodal-ai": ["multimodal", "多模态"],
  };
  
  const tags = baseTags[category] || ["ai"];
  
  // 从标题中提取关键词
  if (title.includes("Agent")) tags.push("agent");
  if (title.includes("微调")) tags.push("fine-tuning");
  if (title.includes("GPT")) tags.push("gpt");
  
  return [...new Set(tags)]; // 去重
}

function main() {
  const articles: ArticleData[] = [];
  const intros: Record<string, Record<string, { content: string; title: string; summary: string }>> = {};

  for (const domain of domains) {
    intros[domain.slug] = {};
    const categories = getCategories(domain.slug);
    
    for (const cat of categories) {
      const catDir = path.join(ARTICLES_DIR, domain.slug, cat.slug);
      
      // 读取该分类下的 HTML 文章
      const files = readHtmlFiles(catDir);
      
      for (const file of files) {
        const title = extractTitle(file.content) || file.slug;
        const summary = extractSummary(file.content);
        const date = getFileDate(file.filePath);
        
        articles.push({
          slug: file.slug,
          domain: domain.slug,
          category: cat.slug,
          title,
          date,
          summary,
          tags: inferTags(cat.slug, title),
          group: inferGroup(cat.slug),
          draft: false,
          content: file.content,
        });
      }
    }
  }

  // 按日期排序
  articles.sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());

  // Generate static content file
  const fileContent = `// Auto-generated static content registry
// Generated at: ${new Date().toISOString()}
// Do not edit this file manually

import type { Article, ArticleMeta, SidebarData } from "@/types";
import { domains, getCategories, getDomain } from "./domains";

// Static article data
const articlesData: Article[] = ${JSON.stringify(articles, null, 2)};

// Static intro data
const introsData: Record<string, Record<string, { content: string; title: string; summary: string }>> = ${JSON.stringify(intros, null, 2)};

// Article registry
export const staticArticles: Article[] = articlesData;

// Get all article slugs for generateStaticParams
export function getAllArticleSlugs(): { domain: string; slug: string }[] {
  return staticArticles.map(a => ({ domain: a.domain, slug: a.slug }));
}

// Get article by domain and slug
export function getArticleBySlug(domain: string, slug: string): Article | null {
  return staticArticles.find(a => a.domain === domain && a.slug === slug) || null;
}

// Get articles by domain
export function getArticlesByDomain(domain: string): ArticleMeta[] {
  return staticArticles
    .filter(a => a.domain === domain)
    .map(({ content, ...meta }) => meta)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// Get articles by category
export function getArticlesByCategory(domain: string, category: string): ArticleMeta[] {
  return staticArticles
    .filter(a => a.domain === domain && a.category === category)
    .map(({ content, ...meta }) => meta)
    .sort((a, b) => new Date(b.date).getTime() - new Date(a.date).getTime());
}

// Get sidebar data
export function getSidebarData(domainSlug: string): SidebarData | null {
  const domain = getDomain(domainSlug);
  if (!domain) return null;
  const categories = getCategories(domainSlug);
  const sidebarCategories = categories.map(cat => {
    const articles = getArticlesByCategory(domainSlug, cat.slug);
    const hasIntro = !!introsData[domainSlug]?.[cat.slug];
    return { ...cat, articles, hasIntro };
  });
  return { domain, categories: sidebarCategories };
}

// Get category intro
export function getCategoryIntro(
  domainSlug: string,
  categorySlug: string
): { content: string; title: string; summary: string } | null {
  return introsData[domainSlug]?.[categorySlug] || null;
}

// Get domain with categories
export function getDomainWithCategories(domainSlug: string) {
  const domain = getDomain(domainSlug);
  if (!domain) return null;
  const categories = getCategories(domainSlug);
  return { ...domain, categories };
}
`;

  fs.writeFileSync(OUTPUT_FILE, fileContent, "utf-8");
  console.log(`Generated static registry with ${articles.length} articles`);
  console.log(`Output: ${OUTPUT_FILE}`);
  
  // 打印生成的文章列表
  console.log("\nGenerated articles:");
  for (const article of articles) {
    console.log(`  - [${article.domain}/${article.category}] ${article.title} (${article.slug})`);
  }
}

main();
